[model]
learning_rate = 1e-4
buffer_size = 1_000_000
batch_size = 256           # 256
learning_starts = 10_000
train_freq = 1
ent_coef = 0.1
target_update_interval = 1
tau = 0.005
gamma = 0.99
gradient_steps = 1

[learn]
total_timesteps = 2_000_000


[env]
n_envs = 64

[eval]
n_envs = 1
freq = 2_000_000
n_episodes = 128

[rng]
seed = 1

[wandb]
project = "lsy_drone_racing"
entity = "amacati"
group = "sac"
