[model]
learning_rate = 3e-4
buffer_size = 200_000
batch_size = 256
learning_starts = 100
train_freq = 1
ent_coef = 0.1
target_update_interval = 1
tau = 0.005
gamma = 0.99
gradient_steps = 64

[learn]
total_timesteps = 1_000_000


[env]
n_envs = 64

[eval]
n_envs = 32
freq = 100_000
n_episodes = 128

[rng]
seed = 1

[wandb]
project = "lsy_drone_racing"
entity = "amacati"
group = "sac"
