[model]
learning_rate = 1e-3
buffer_size = 200_000
learning_starts = 100
batch_size = 256
tau = 0.005
gamma = 0.99
train_freq = 1
gradient_steps = 32
policy_delay = 2
target_policy_noise = 0.2
target_noise_clip = 0.5

[model.action_noise]
type = "NormalActionNoise"
[model.action_noise.kwargs]
mean = 0.0
sigma = 0.2

[learn]
total_timesteps = 500_000


[env]
n_envs = 64

[eval]
n_envs = 32
freq = 100_000
n_episodes = 128

[rng]
seed = 1

[wandb]
project = "lsy_drone_racing"
entity = "amacati"
group = "td3"
