lr = 3e-4
buffer_size = 1e6
batch_size = 256
learning_starts = 100
train_freq = 1
ent_coef = "auto"
target_update_interval = 1
tau = 0.005
gamma = 0.99
gradient_steps = 1

n_envs = 64
n_timesteps = 1_000_000

eval_freq = 10_000
n_eval_episodes = 128

[rng]
seed = 1

[wandb]
project = "lsy_drone_racing"
entity = "amacati"
group = "sac"
