lr = 3e-4
buffer_size = 1e6
batch_size = 512
learning_starts = 10_000
train_freq = 1
ent_coef = 0.2
target_update_interval = 1
tau = 0.005
gamma = 0.99
gradient_steps = 1

n_envs = 64
n_timesteps = 10_000_000

eval_freq = 1_000
n_eval_episodes = 128

[rng]
seed = 1

[wandb]
project = "lsy_drone_racing"
entity = "amacati"
group = "sac"
